const shortcutsListGmail = [
    {description: "К предыдущему сообщению в открытой цепочке",
    keys:["P","Tab"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}
    },
    {description: "К следующему сообщению в открытой цепочке",
    keys:["N"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    
    {description: "Переместить курсор на панель инструментов",
    keys:[","],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Выбрать цепочку писем",
    keys:["X"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Выбрать одну из пометок",
    keys:["S"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "К последнему чату или окну создания сообщения",
    keys:["Esc"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Архивировать",
    keys:["E"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Игнорировать цепочку писем",
    keys:["M"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
   

    {description: "Назад к списку цепочек",
    keys:["U"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Перейти к следующей цепочке писем",
    keys:["K"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Ответить",
    keys:["R"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Ответить всем",
    keys:["A"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Переслать",
    keys:["F"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Отменить последнее действие",
    keys:["Z"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Отметить как непрочитанные, начиная с выбранного сообщения",
    keys:["-"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Отложить",
    keys:["B"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Развернуть цепочку",
    keys:[";"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Открыть цепочку",
    keys:["J"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}}, 

    {description: "Свернуть цепочку",
    keys:[":"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}}, 
    {description: "Отправить в спам",
    keys:["!"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Удалить",
    keys:["#"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},


    {description: "К главному окну",
    keys:["Shift","Esc"],
    instruction: {h2: "Отключить бесконечную и неважную цепочку (m)",
                  description: "Если вы каким-то образом попали в неинтересную вам цепочку писем, нажмите на m, чтобы начать игнорировать ее. Любые новые сообщения этой ветки будут автоматически архивироваться.",
                  source: ""}},
    
    {description: "К следующему чату или окну создания сообщения",
    keys:["Ctrl", "."],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "К предыдущему чату или окну создания сообщения",
    keys:["Ctrl",","],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Открыть дополнительный адрес отправителя",
    keys:["Ctrl", "Shift", "F"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Отправить",
    keys:["Ctrl", "Ввод"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Добавить копию",
    keys:["Ctrl","Shift","C"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},
    {description: "Добавить скрытую копию",
    keys:["Ctrl","Shift","C"],
    instruction: {h2: "not yet",
    description: "not yet",
    source: ""}},  
];



export {shortcutsListGmail}; 