const shortcutsListGmail = [
    {description: "Previous message in an open conversation",
    keys:["P"]},
    {description: "Next message in an open conversation",
    keys:["N"]},    
    {description: "Move focus to toolbar",
    keys:[","]},
    {description: "Select conversation",
    keys:["X"]},
    {description: "Toggle star/rotate among superstars",
    keys:["S"]},
    {description: "Focus latest chat or compose",
    keys:["Esc"]},
    {description: "Archive",
    keys:["E"]},
    {description: "Mute conversation",
    keys:["M"]},
   

    {description: "Back to threadlistк",
    keys:["U"]},
    {description: "Newer conversation",
    keys:["K"]},
    {description: "Reply",
    keys:["R"]},
    {description: "Reply all",
    keys:["A"]},
    {description: "Forward",
    keys:["F"]},
    {description: "Undo last action",
    keys:["Z"]},
    {description: "Mark unread from the selected message",
    keys:["_"]},
    {description: "Snooze",
    keys:["B"]},
    {description: "Expand entire conversation",
    keys:[";"]},
    {description: "Older conversation",
    keys:["J"]},

    {description: "Report as spam",
    keys:["!"]}, 
    {description: "Delete",
    keys:["#"]},      
    {description: "Focus main window",
    keys:["Esc", "Shift"]},
    {description: "Send",
    keys:["Ctrl", "Enter"]},
    {description: "Advance to the next chat or compose",
    keys:["Ctrl", "."]},
    {description: "Advance to previous chat or compose",
    keys:["Ctrl", ","]},



    {description: "Collapse entire conversation",
    keys:[":"]},
    {description: "Add cc recipients",
    keys:["Ctrl", "Shift", "C"]},
    {description: "Add bcc recipients",
    keys:["Ctrl", "Shift", "B"]},
    {description: "Mark as not important",
    keys:["-"]},
    {description: "Access custom from",
    keys:["Ctrl", "Shift", "F"]},
    {description: "Insert a link",
    keys:["Ctrl", "K"]},
    {description: "Open spelling suggestions",
    keys:["Ctrl", "M"]},
    {description: "Previous font",
    keys:["Ctrl", "Shift","5"]},
    {description: "Next font",
    keys:["Ctrl", "Shift","6"]},
    {description: "Decrease text size",
    keys:["Ctrl", "Shift","-"]},
    {description: "Increase text size",
    keys:["Ctrl", "Shift","+"]},
    {description: "Bold",
    keys:["Ctrl", "b"]},
    {description: "Italics",
    keys:["Ctrl", "i"]},
    {description: "Underline",
    keys:["Ctrl", "u"]},
    {description: "Numbered list",
    keys:["Ctrl", "Shift","7"]},
    {description: "Bulleted list",
    keys:["Ctrl", "Shift","8"]},
    {description: "Quote",
    keys:["Ctrl", "Shift","9"]},
    {description: "Indent less",
    keys:["Ctrl", "["]},
    {description: "Indent more",
    keys:["Ctrl", "]"]},
    {description: "Align left",
    keys:["Ctrl", "Shift","L"]},
    {description: "Align center",
    keys:["Ctrl", "Shift","e"]},
    {description: "Align right",
    keys:["Ctrl", "Shift","r"]},
    {description: "Remove formatting",
    keys:["Ctrl", "\\"]},
    {description: "Add conversation to Tasks",
    keys:["Shift", "t"]}    
];



export {shortcutsListGmail}; 